force-app/main/default/objects/Color__c/Color__c.object-meta.xml
<CustomObject>
    <label>Color</label>
    <nameField>
        <label>color</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Color__c/fields/AccountColor__c.field-meta.xml
<CustomField>
    <fullName>AccountColor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colors</relationshipLabel>
    <relationshipName>Colors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Color__c/fields/colorCode__c.field-meta.xml
<CustomField>
    <fullName>colorCode__c</fullName>
    <label>Color code</label>
    <length>7</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Color__c/fields/colorDate__c.field-meta.xml
<CustomField>
    <fullName>colorDate__c</fullName>
    <label>colorDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ParsingJsonDai.cls
public with sharing class ParsingJsonDai {
    
@AuraEnabled
     public static Color getColor(String cuentaId) {  

                Http httpProtocol = new Http();
                HttpRequest request = new HttpRequest();
                String endpoint = 'https://apitestjefersonsf2.herokuapp.com/avalian/get-color';
                request.setEndPoint(endpoint);
                request.setMethod('POST');
                request.setBody('{ "accountId" : "' + cuentaId + '"}');
                request.setHeader('Content-Type', 'application/json');
                HttpResponse res = httpProtocol.send(request);

                Color colorMio = new Color();
                Color__c colorSf = new Color__c();

                  System.debug(res.getStatusCode()); //400

                if(res.getStatusCode()== 200){
                    
                    colorMio = (Color) JSON.deserialize(res.getBody(), Color.class);
                    colorMio.setAccountId(cuentaId);
                    colorMio.setSuccessful(true); 

     System.debug('El id color' + colorMio.getAccountId());

                    colorSf.colorCode__c = colorMio.colorCode;
                    colorSf.colorDate__c = datetime.now();               
                    colorSf.Name = colorMio.color;
                    colorSf.AccountColor__c = colorMio.accountId;

                    insert colorSf; //No esta funcionando el insert
                } else {
                      colorMio.setSuccessful(false); 
                }

                System.debug(colorSf);
           System.debug(colorMio);

      return colorMio;
}

@AuraEnabled
      public static Color__c getLatest(String cuentaId) {
           
           List<Color__c> colorSf = new List<Color__c>();
            colorSf = [SELECT name, colorDate__c, colorCode__c FROM Color__c WHERE AccountColor__c = :cuentaId ORDER BY colorDate__c DESC LIMIT 1];
         
            Color__c color1;

            if(colorSf.size()>0){
                 color1 = colorSf.get(0); 
                 System.debug('La fecha del color brindado por la consulta SOQL es: ' + color1.colorDate__c);
                  return color1;
            } else{
                  return null;
            }
           
      }
      

}